### ISSUE TITLE
The Seed Bank

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#11]
Publish vaults and share them with others. Should support:

- [] mechanism for publishing a vault 
- [] mechanism for viewing a vault
- [] mechanism for forking a vault
- [] mechanism for supporting a **pull request** to a vault
- [] design for private vaults (implementation out of scope)

**Comment by kpathakota** [comment]
Details: https://www.dendron.so/notes/b81810f7-4d47-4870-ad2c-d4e48a49aa22
