### ISSUE TITLE
Include note references when publishing

### ISSUE THREAD

**Issue by buxel** [dendronhq/dendron#134]
It would be great if note references would also get exported when publishing my notes. 
This way, sharing with colleagues will be much easier.

(also, it could help with aggregated TODO's in the future)

**Comment by kevinslin** [comment]
# Tasks
- [x] create a remarkable plugin that can recognize ref links, see [this](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/topics/markdown/plugins/dendronLinksPlugin.ts#L1:L1) as an example
- [x] add plugin to remarkable processor [here](https://github.com/dendronhq/dendron/blob/master/packages/engine-server/src/topics/markdown/utils.ts#L392:L392)
- [ ] use note ref plugin when building site
- [ ] add docs
- [ ] add tests

**Comment by kevinslin** [comment]
shipped in dbd50d6
