### ISSUE TITLE
Use `remark-variables` for custom frontmatter variable substitution

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#1626]
## Summary
- Use `remark-variables` for frontmatter variable substitution instead of Nunjucks

## Details
- Nunjucks if useful for a lot of things but we are only using it do frontmatter variable substitution in the note body.
- We should use `remark-variables` instead

## Tasks
- [ ] Remove calls to `nunjucks.renderString()`
  - This happens in two places:
    - `DendronEngineV2._renderNote()`
      - To render a note
    - `NoteRefsV2.convertNoteRefHelperAST()`
      - To render a note reference
- [ ] Add plugin `remark-variables` to processors and add the `fm` object to the processor's `.data`
  - Examples can be found [here](https://github.com/mrzmmr/remark-variables)
- [ ] Add tests
- [ ] Update documents on variable substitution.

## Lookup
- page for remark plugin
  - https://github.com/mrzmmr/remark-variables
- example in dendron codebase
  - where the plugin is set
    - https://github.com/dendronhq/dendron/blob/c07c6724419ba506198a316e5b8aa4ab06b74ab7/packages/engine-server/src/markdown/utils.ts#L402
  - where the `fm` object is passed to the processor
    - https://github.com/dendronhq/dendron/blob/c07c6724419ba506198a316e5b8aa4ab06b74ab7/packages/engine-server/src/markdown/utils.ts#L382
- current docs on variable substitution
  - https://wiki.dendron.so/notes/ba97866b-889f-4ac6-86e7-bb2d97f6e376/#frontmatter-variable-substitution
- where note rendering is tested
  - https://github.com/dendronhq/dendron/blob/0282c1703643995b6675ee6ee64ca7c7b7500fd2/packages/engine-test-utils/src/presets/engine-server/render.ts
- where note reference rendering is tested
  - https://github.com/dendronhq/dendron/blob/0282c1703643995b6675ee6ee64ca7c7b7500fd2/packages/engine-test-utils/src/presets/engine-server/note-refs.ts
- where nunjucks is currently used
  - https://github.com/dendronhq/dendron/blob/c07c6724419ba506198a316e5b8aa4ab06b74ab7/packages/engine-server/src/markdown/remark/noteRefsV2.ts#L780
  - https://github.com/dendronhq/dendron/blob/0282c1703643995b6675ee6ee64ca7c7b7500fd2/packages/engine-server/src/enginev2.ts#L569
  - https://github.com/dendronhq/dendron/blob/16b0e5c59e3ee11530199b5c9a11a58f05e14a93/packages/dendron-11ty/libs/shortcodes.js#L129

**Comment by ratsey** [comment]
This [issue](https://github.com/mrzmmr/remark-variables/issues/3) from a year ago would suggest that remark-variables is going to stop working.
Would you consider an alternative and [switch from nunjucks to etl](https://github.com/dendronhq/dendron/issues/1602)?

**Comment by hikchoi** [comment]
This has been shipped! 🥳
