### ISSUE TITLE
Pods v0

### ISSUE THREAD

**Issue by kpathakota** [dendronhq/dendron#167]
# Pods v0

## Goal	

Make it possible for people to import/export their data between Dendron and **any other** platform that contains information a user might care about.	

## Tasks
- [x] establish basic pod framework
- [x] use pods via extension
- [x] use pods via CLI
- [x] create 2 pods
- [ ] support custom pods
- [ ] document pods

## Next
- community voting on pods
- stabilize pod API

# Links
- [project docs](https://dendron.so/notes/b1dbd32d-ca87-4489-9ba0-01bf7928cba5.html)
- [issues](https://github.com/dendronhq/dendron/labels/pro.pods-v0)

**Comment by kpathakota** [comment]
Pods in their current state are done *I think* - @kevinslin - can you confirm and close?
