### ISSUE TITLE
Teach dendron about .todo.md not being a hierarchy

### ISSUE THREAD

**Issue by chmac** [dendronhq/dendron#2276]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Sharing data between other tools and dendron can result in extra hierarchies because dendron treats any `.` as a hierarchy separator. Yet some other programs use double extensions.

## Describe the solution you'd like ##

I want to share data between tools like [nb](https://xwmx.github.io/nb/) and dendron. nb stores bookmarks in files called `name.bookmark.md`. I want to be able to tell dendron to not treat `.suffix.md` as a separate hierarchy. I can imagine having multiple such suffixes.

I'd like to be able to specify a list of suffixes on a per-vault or per-workspace level. Ideally both options would be concatenated together on the vault level. As in, my whole workspace could say `.todo.md` is an extension not a hierarchy, and in one vault my config could say `.bookmark.md` is an extension not a hierarchy. Then any `.todo.md` files in my bookmark vault would also be treated as an extension and not a hierarchy.

## Describe alternatives you've considered ##

Can't see any alternatives unfortunately, except simply accepting the problem.

## Additional context ##

The dendron schemas seem to do similar, with `.schema.yml`.

**Comment by kevinslin** [comment]
Heads up, I wrote a very early draft of what supporting other file types could look like in Dendron: https://github.com/dendronhq/dendron-docs/blob/utility-convention/vault/rfc.40-arbitrary-plaintext-file-vaults.md#L60:L60

Also discussion thread in discord -> https://discord.com/channels/717965437182410783/936029538998190090/936029542538178660
