### ISSUE TITLE
Server Migration

### ISSUE THREAD

**Issue by kevinslin** [dendronhq/dendron#234]
# Server Migration

## Goals

Migrate the Dendron to client <-> server architecture

## Details

Dendron's current architecture can be found [here](https://dendron.so/notes/c160ddce-edec-4f6e-841b-418d6030fa37.html). Currently, all of Dendron's indexing capabilities is provided by the `dendron engine` as a library which is included in every extension that uses it. This has many drawbacks - every extension re-indexes all notes and also blocks the client (vscode) during this process.

The Dendron server migration is to move Dendron to a client server architecture. Note that the migration will involve standing up **two servers**: one for language server functionality (the lsp server), and another for dendron's [lookup](https://dendron.so/notes/a7c3a810-28c8-4b47-96a6-8156b1524af3.html) capabilities (the express server). 

The rationale for having two servers is discussed [here](https://discordapp.com/channels/717965437182410783/748936364283920495/759153642644701285).

Instead of calling the engine directly, the Dendron extension, as well as related plugins, will communicate to Dendron's server using IPC and on local ports. 

## Tasks
- [x] add LSP server to Dendron
- [x] add Express server to Dendron
- [x] migrate lookup to server model
- [x] migrate all current functionality to server model

## Next
- use custom goto definition provider 
- use custom backlink definition provider
- use schema based completions
- migrate bundled extensions to server model

## Links
- [project docs](https://dendron.so/notes/725d99be-fadd-4464-88c3-0a5fcc7292c7.html)
- [issues](https://github.com/dendronhq/dendron/labels/pro.server-migration)

**Comment by kpathakota** [comment]
Details: https://www.dendron.so/notes/725d99be-fadd-4464-88c3-0a5fcc7292c7

**Comment by drkstr101** [comment]
Greetings all!

I am very happy to have stumbled upon this issue while doing some research to see if my `theia-dentrite` project. Very smart move going with LSP client-server model!

[Theia IDE](theia-ide.org/) is a cloud-first IDE which is able to use plug-ins off Open VSX registry. You may be interested to know that many Dendron features just work out-of-the-box in Theia.

I was going to put in the work to take it the rest if the way, so maybe we should colaborate? It would be ideal if this work could be done in mainline, rather than maintaining separate fork.

This project will serve as the Knowledgebase for a startup I'm launching in Jan, so maybe, hopefully, we can even staff someone to contribute to Dendron. Wishful thinking, I know. 😄

I realize this epic is pretty much over, but maybe on the next one? Let me know what your thoughts are.

Cheers, and thank you for Dendron!

**Comment by kevinslin** [comment]
I'm familiar with Theia and monitoring its progress. As for knowledge base, I think our goals intersect in quite a few places. Lets talk more. You can message me at kevin@dendron.so
