### ISSUE TITLE
Journal Template Not Applied

### ISSUE THREAD

**Issue by eddy-murj** [dendronhq/dendron#2374]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [x] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

As of yesterday's patch, my journal template is no longer being applied through my schema.

## To Reproduce

I have a journal schema (daily.schema.yml) file like so:

```yaml
version: 1
imports: []
schemas:
- id: daily
  title: daily
  parent: root
  children:
    - journal
- id: journal
  title: journal
  parent: root
  children:
    - year
- id: year
  title: year
  pattern: "[0-9][0-9][0-9][0-9]"
  children:
    - month
- id: month
  title: month
  parent: year
  pattern: "[0-9][0-9]"
  children:
    - day
- id: day
  title: day
  parent: month
  pattern: "[0-9][0-9]"
  namespace: true
  template:
    id: templates.daily.journal
    type: note

```

And a journal template (templates.daily.journal.md):

```md
---
id: zDVh8WCuvQXHp9p0wcxsb
title: Daily Journal Template
desc: ''
updated: 1643390819226
created: 1643389274001
stub: false
---

## Meetings

- [ ] xxxxxx
- [ ] ... @ hh:mm

## Tasks

- [ ] ...
- [ ] ...

## Notes

- ...

```

1. Open up the command palette and select "Dendron: Create Daily Journal Notes"
2. Observe the journal file being created not containing the template.

## Expected behavior

Up until yesterday (2022-02-07), the template would populate fine, but since the latest update, this no longer works.

## Screenshots

none.

## Desktop (please complete the following information)

- OS: MacOS Monterey 12.02 (on an M1 MacBook Pro, if that matters)
- Browser: Google Chrome
- Version: 97.0.4692.99
- VSCode: Version 1.64.0

## Additional context

None

## Dendron Log file

```json
{"level":30,"time":1644343182641,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1644343182641,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1644343182642,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/eddy/code/notes/vault/daily.schema.yml"]}
{"level":30,"time":1644343182644,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/eddy/code/notes/vault/daily.schema.yml"}
{"level":30,"time":1644343184896,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"dendron.createDailyJournalNote:run","msg":"pre-execute"}
{"level":30,"time":1644343184896,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"CreateNoteWithTraitCommand","msg":"enter","opts":{"title":"daily.journal.2022.02.08","fname":"daily.journal.2022.02.08"}}
{"level":30,"time":1644343184903,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"/Users/eddy/code/notes/vault/daily.schema.yml"}
{"level":30,"time":1644343184903,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1644343184903,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"daily.journal.2022.02.08","vault":{"fsPath":"vault"},"overrides":{"title":"2022-02-08","traits":[{"id":"journalNote","OnWillCreate":{},"OnCreate":{}}]}},"msg":"enter"}
{"level":30,"time":1644343184914,"pid":24534,"hostname":"Eddys-MacBook-Pro.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1644343184921,"pid":24534,"hostname":"Eddys-MacBook-Pro.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1644343184931,"pid":24534,"hostname":"Eddys-MacBook-Pro.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1644343184940,"pid":24534,"hostname":"Eddys-MacBook-Pro.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1644343184969,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1644343184969,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1644343184974,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/eddy/code/notes/vault/daily.journal.2022.02.08.md"]}
{"level":30,"time":1644343184975,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/eddy/code/notes/vault/daily.journal.2022.02.08.md"}
{"level":30,"time":1644343184982,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"daily.journal.2022.02.08"}
{"level":30,"time":1644343184983,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"exit","fname":"daily.journal.2022.02.08"}
{"level":30,"time":1644343184985,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"GotoNoteCommand","opts":{"qs":"daily.journal.2022.02.08","vault":{"fsPath":"vault"},"overrides":{"title":"2022-02-08","traits":[{"id":"journalNote","OnWillCreate":{},"OnCreate":{}}]}},"msg":"exit"}
{"level":30,"time":1644343184985,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"CreateNoteWithTraitCommand","msg":"exit"}
{"level":30,"time":1644343184985,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"dendron.createDailyJournalNote:run","msg":"post-execute"}
{"level":30,"time":1644343184992,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"FileWatcher:onDidCreate","fsPath":"/Users/eddy/code/notes/vault/daily.journal.2022.02.08.md"}
{"level":30,"time":1644343185033,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1644343185094,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"refreshTree"}
{"level":30,"time":1644343188274,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1644343188274,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1644343188274,"pid":24525,"hostname":"Eddys-MacBook-Pro.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/eddy/Library/Application Support/Code/logs/20220208T114531/exthost4/dendron.dendron/dendron.log"]}
```

**Comment by Harshita-mindfire** [comment]
Hey @eddy-murj , Thanks for reporting the bug. Looks like the attached schema is problematic. You would want to update the parent of `journal` to `daily` instead of `root`
```yml
version: 1
imports: []
schemas:
- id: daily
  title: daily
  parent: root
  children:
    - journal
- id: journal
  title: journal
  parent: root ----> daily
  children:
    - year
  ```

**Comment by eddy-murj** [comment]
@Harshita-mindfire well, that was silly. That fixed it 😅  Sorry to litter your backlog with what turned out to be aa troubleshooting issue.

Thanks so much for the quick help!
