### ISSUE TITLE
Feature request: TODO summary view

### ISSUE THREAD

**Issue by falcomomo** [dendronhq/dendron#3400]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When I was using org-mode I found the org-agenda view very useful.
From the [org-mode docs](https://orgmode.org/manual/Agenda-Views.html): 

> Due to the way Org works, TODO items, time-stamped items, and tagged headlines can be scattered throughout a file or even a number of files. To get an overview of open action items, or of events that are important for a particular date, this information must be collected, sorted and displayed in an organized way.
> 
> Org can select items based on various criteria and display them in a separate buffer. Six different view types are provided:
> 
> - an agenda that is like a calendar and shows information for specific dates,
> - a TODO list that covers all unfinished action items,
> - a match view, showings headlines based on the tags, properties, and TODO state associated with them,
> - a text search view that shows all entries from multiple files that contain specified keywords,
> - a stuck projects view showing projects that currently do not move along, and
> -custom views that are special searches and combinations of different views.

## Describe the solution you'd like ##

I think at least a summary of todo items would be good to have in Dendron, which could either be in the side bar as a View or as a special note which gets updated through a function.

## Describe alternatives you've considered ##

I think using the built in VS Code search functions like in [Kevin's here](https://wiki.dendron.so/notes/593206ea-5658-4874-bafd-18a138870f91/) is ok but not great.

## Additional context ##

- [A video of org-mode agenda views](https://www.youtube.com/watch?v=7ybg3vjLQJM)

- [A much longer video](https://www.youtube.com/watch?v=Ea_-TaEGa7Y)

- [Blog about org-mode agenda](http://cachestocaches.com/2016/9/my-workflow-org-agenda/)

-

**Comment by hikchoi** [comment]
Thank you for the feature request.

The way we currently recommend doing this is by creating [tags](https://wiki.dendron.so/notes/8bc9b3f1-8508-4d3a-a2de-be9f12ef1821/)

So in this case you would have a note called `tags.TODO`, and prepend them to todo items like so:

```milk
#TODO buy milk
```

If you navigate to the note `tags.TODO`, you will have the backlinks view with all the todo item.

Would this be sufficient for your use case?

**Comment by xmailla** [comment]
Org-mode agenda is a dedicated and specialised view:

[See this](
![](http://cachestocaches.com/media/photologue/photos/cache/org-agenda-features_display.jpg)
)

`tags.TODO` is a good start (that can even work for any other page in Dendron) but it is far far away the Org-mode agenda feature IMO.

**Comment by hikchoi** [comment]
I agree with your sentiment. I wasn't suggesting that using tags for this use case is a direct replacement for `org-agenda`.

I am not a org-mode user so I'm not too familiar with the experience with these features, but I can generally agree that these sort of convenience around a very very core use case (task management) would help a lot.

I cannot say that the experience would directly translate into Dendron, but we are always looking for ways to provide more feature around task management, so thank you all for the feedback on this. `org-agenda` definitely seems like an interesting approach. We'll keep this in mind when we enhance features around task management.

**Comment by ldartez** [comment]
I would also like to support this feature request. In particular the agenda and todo list views are important to me. The workaround suggested with tags in Dendron is interesting, but it doesn't mix well with org-mode's use of tags, properties, and TODO states (very important for tracking progress, etc.).

**Comment by caseydierking** [comment]
I too would support this request. It feels like having a place that summarizes all open Todos (Kind of like Todo Tree) would be really helpful. For that matter, having a place the summarizes all task notes would be even better. I'm currently trying to find my workflow with this right now. Copying and pasting links to those todo items into a general note feels redundant to me.
