### ISSUE TITLE
TODO migration to a new page on daily journal

### ISSUE THREAD

**Issue by zzzz465** [dendronhq/dendron#3878]
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I use dendron for writing and organizing daily todos on the daily journal page.
there are some tasks that haven't been finished on that day, I moved them to the new page the next day.

## Describe the solution you'd like ##

usually, they're noted under `## TODO`, so collecting items and moving them when creating a new daily journal page would be great.

## Additional context ##

the example TODO would be like...

```md
## TODO

today's tasks

- [ ] write a report email to my boss
- [x] clear 7 unused EC2 instances
- [x] update deprecated packages
- [ ] attend a daily scrum
- [x] finish feature/XXX

yesterday's unfinished tasks

- [ ] pet a cat
- [ ] clean my room
- [ ] call the hospital for an annual health check-up reservation
```

also, is dendron accepting PR from anyone?

**Comment by jumar** [comment]
Yep, something like this would be great: Automatically copy to new daily note the unfinished tasks from the previous day (while keeping their section's title)

```
## TODO (my tasks)
- [X] task 1
- [ ] task 2
- [ ] task 3

## To follow-up (other people's tasks)
- [ ] task 4
- [X] task 5
```

Would be transferred to the next day's daily note as:

```
## TODO (my tasks)
- [ ] task 2
- [ ] task 3

## To follow-up (other people's tasks)
- [ ] task 4
```
