### ISSUE TITLE
Suggestions for Dendron tasks/todo, export and other features

### ISSUE THREAD

**Issue by FelipoAntonoff** [dendronhq/dendron#3902]
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [x] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [x] Pod - Data import from / export to Dendron
- [x] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Here are some suggestions to improve some Dendron features, mainly Tasks/TODO:

- Support for start target date and end target date (deadline)
- Support for recurring/repeating tasks and habits, for example paying credit card bills, paying internet or habits like training day X, Y, Z, opening email at X, Y, Z time
- Support for Time Tracking/Time Log, keeping the time history of a task, registering a log of when it started and ended, so that the task can have the state started, paused and finished, for example, Orgmode is the best example of this feature, there is also Taskwarrior
- Support to generate timelog report (task time recording)
- View tasks in a calendar according to the scheduled start date and scheduled finish date
- Being able to see if a task is late on the scheduled start and/or end date
- View tasks in tables summarizing your data and even being able to make small queries such as tasks of the day, tasks of the week, tasks in 30 days
- Display in the parent task, the % of completed based on the closing of the sub tasks, example: It has a parent task Shopping and added 10 products, if marked as completed 5 of the sub tasks, in the main it displays 50%, a good example is the WHOLE of Orgmode
- Inform the expected time/effort to do a task, for example 30 minutes, 1 hour, 10 days
- Relationship and dependency between tasks, for example: you solved a task and when you created another one, you know that in the previous one there are concepts that can help, so in the new one, mark the previous one to remember or it could be dependency, a task that is meant to be started after or before another task
- Quick task creation, maybe some shortcut that already creates a task or note in a temporary file
- Web Clipper to be easy to import contents, links and maybe even turn an email in Zoho, Gmail and the like into a task
- Add in the documentation examples of systems that support exporting notes/documents to some static site generator such as MkDocs, Hugo, Jekyll or Pelican for example, thus encouraging the use of Dendron for a greater scope, being able to replace even Sites, Blogs, Public and private Wikis and Knowledge Base. I think the best and simplest solution would be MkDocs with this theme https://squidfunk.github.io/mkdocs-material/, as it is made in Python and simple to use, another option and one of the most popular is Hugo made in Go, it will perform better
- Being able to create a main page when exporting to a Site, so that a home page can be created for a company, portfolio or other uses, for example the Dendron home page https://www.dendron.so/ and About https: //www.dendron.so/about, these are personalized and very well done pages, they could even be generated by the Dendron exporter, perhaps having a separate theme or even a base theme, but basically created with HTML or a Template Engine like Twig , Jinja 2 and the like, a good example of this is MkDocs, we can define what the home page is, I think Hugo has the same feature too, although maybe this feature can be implemented externally by the chosen static site generator, but if Dendron is the generator of the static site itself it would be interesting, the idea would be to centralize the use of Dendron, so it would no longer be necessary for most cases to have a CMS, Site, Wiki, Blog, Project and Task Manager, Annotation systems and knowledge base, since Dendron is very rich in several resources that most systems cannot have, even because Dendron uses VS Code which already makes it possible to create a type of Org mode that is simpler to use and more modern
- The most important thing about exporting is keeping the default folders and tagging of static site generators, maybe even just focusing on sending them to their content folder, since the theme part and other resources can already be configured in them.

Note: I haven't used Dendron for a while, I'm starting to use it again to see if I can centralize it for basically every use case related to the website, blog, documentation, notes, tasks, projects and other uses, before I used Dokuwiki and others tools, but I'm not satisfied, mainly in the way of editing and organization that I consider Dendron superior.
So please disregard if any of the suggestions have already been implemented in more current versions or because I still have an initial knowledge of Dendron.

Thanks for creating Dendron, it has helped a lot in my internal organization and in the future I intend to use it to replace my Wiki and probably Site/Blog.

## Describe the solution you'd like ##

Some suggestions mentioned in the text above

## Describe alternatives you've considered ##

**References:**
I believe the best task system using text file and keyboard shortcuts is Org Mode: https://orgmode.org/
It has all the resources cited and more for reference, some on TODO https://orgmode.org/manual/TODO-Items.html and https://orgmode.org/worg/org-tutorials/orgtutorial_dto.html which you can see at the end the agenda feature, scheduling, timelog

https://www.mylifeorganized.net/ - Very interesting note system, good example on the date to start and end a task, as there are tasks that, for example, expire on 03/30/2023, but it is a task that can be started before, for example Buying a gift for the wife's birthday, the due date would be her birthday and the scheduled start date would be, for example, 1 month before, so when the next 1 month arrives, the system already shows it in the week's tasks for example, but being able to start later is no problem, but having an idea of when it would be ideal to start

https://www.2doapp.com/ - Good task concepts, simpler than My Life Organized, but a good quick reference and perhaps as close as Dendron can be to features as it's not as complete, it just lacks it record time basically and support multiple levels of sub tasks

https://taskwarrior.org/ - Good cli task system, has the concepts of scheduling, recurrence, reports and others
https://timewarrior.net/ - Good example to time and log a task
https://www.redmine.org/projects/redmine/wiki/redminetimetracking - Example of Time Tracking resource in a more manual way, being able to inform the time, note, activity done

https://www.mediawiki.org/wiki/MediaWiki and https://www.dokuwiki.org/dokuwiki are great references on Dendron's annotation features, they have very interesting include, annotation, citation, organization features of images and files, version and many other resources that can serve as good references for Dendron. A very interesting resource is the Sematic MediaWiki https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki, good for query data reference and data table, can be used in Dendron to organize notes, tasks, images, files and other uses, Obsidian also has a query feature

https://squidfunk.github.io/mkdocs-material/ - Example of the idea of the landing page, made use of MkDocs and the Material theme integrated into it, as we can see even though it is a system focused on Documentation, it managed to create a beautiful and informative homepage for your product/company

## Additional context ##

N/A
