### ISSUE TITLE
Color of page link is wrong when immediately following a TODO [w]

### ISSUE THREAD

**Issue by M-Fabian** [dendronhq/dendron#3991]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The syntax highlighting for page links immediately following a TODO bracket `[ ]` fails if the bracket contains something else than a space or an `x`. It looks to me as if it was interpreted as a link of the form `[caption](link)`. Despite the wrong syntax highlighting, the links work normally.

## To Reproduce

Add the following text to any dendron page. The TODOs 5 and 6 are highlighted incorrectly.

- [x] [[notes]] Existing page, blue link.
- [x] [[doesnotexist]] Non-existing page, yellow link.
- [ ] [[notes]] Existing page, blue link.
- [ ] [[doesnotexist]] Non-existing page, yellow link.
- [w] [[notes]] The link works but the syntax highlighting is wrong.
- [w] [[doesnotexist]] Same here.
- [w] Text before the link fixes syntax highlighting [[notes]] as shown here.
- [w] Same here [[doesnotexist]].

## Expected behavior

I expect the syntax highlighting to be correct. At least TODO brackets containing the characters suggested in the [documentation](https://github.com/dendronhq/dendron-site/tree/master/vault/dendron.guides.workflows.todos.md) should work.

## Screenshots

![screenshot](https://github.com/user-attachments/assets/1964ddcb-a9ad-44f7-9e35-d048ccbc2cbc)

## Desktop (please complete the following information)

- OS: Windows 10
- Versions (all that apply to bug):
  - Dendron Extension: v0.124.0
  - VS Code version: 1.85.2
  - Dendron CLI:
