### ISSUE TITLE
Make the current root note(root.md) still be recognized as the root of your vault even when the note's file name is changed.

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#483]
## Context
Related to #482 

## Proposal

Short version:

> AS-IS: `root.md` and `root.schema.yml` is reserved to be the `root` of a vault and cannot be changed.
> TO-BE: Some form of `root` still exists, but the name can be anything.

Long version:

Make the current root note (`root.md`) still be recognized as the _root_ of the vault even if it is renamed to something other than `root`.
This will allow users to configure what their root will be named instead of having a _proxy root_ 

Better yet, prompt user to input a preferred name for their root note name and keep `root.md` as the default option.
I'm thinking with this change, `Rename Note` and `Move Note` should also check if the user is trying to rename the root note and rename the root schema with it as well.

I imagine a lot of tests were written with the assumption that `root.md` will never change, so there's going to be some broken tests if this change happens 😇 

What I mean by _proxy root_ : 
![image](https://user-images.githubusercontent.com/1219789/107821582-12b60800-6dc0-11eb-9c13-33abbb5d1e48.png)

## Tasks
- [ ] Make root recognizable even after rename
- [ ] Make `Rename Note`, `Move Note`, `Doctor` commands et. al accommodate this change
- [ ] Fix everything that breaks because of this change
- [ ] (maybe) Add prompt to configure root note name upon vault creation.
