### ISSUE TITLE
Add block ref support.

### ISSUE THREAD

**Issue by manunamz** [dendronhq/dendron#560]
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [x] Markdown
- [ ] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure) -> linking methods

## Is your feature request related to a problem? Please describe ##

I am unable to import obsidian notes into Dendron easily, if there are many block-level links.

## Describe the solution you'd like ##

I would like to be able to link to individual blocks/bullets in my notes.
This is what Obsidian uses -- see [help docs](https://publish.obsidian.md/help/How+to/Link+to+blocks) for details: `[[link#^block_id]]`
(I want to say Foam was talking about/did implement this as well)

## Describe alternatives you've considered ##
N/A

## Additional context ##
N/A

**Comment by kpathakota** [comment]
+2 to the vote total here (closed the linked duplicate).

**Comment by manunamz** [comment]
Just want to add something I just realized -- I figured dendron, the tree-friendly linking app, would be particularly interested. [Here](https://forum.obsidian.md/t/allow-subtree-or-raw-link-specification-in-embeds-and-link-preview-windows/19026) is the link to my obsidian feature request. Text mostly-copy-pasta'd below:

### Background

Obsidian currently supports file, header, and block/bullet level link embeds.

Some current behavioral details:

- Header level link embeds show all content until either the next header of the same level or the end of the file is reached.
- Block level link embeds show the content of the linked block/bullet. 

### Use case or problem

Sometimes I want to see header level link behavior for blocks. For example, with a file of this format:

```
# Heading
- Spec 1
    - Detail A
    - Detail B
    - Detail C
- Spec 2
.
.
.
```

I might want to embed all the content from `Spec 1`, but I don't want it to be rendered as a heading.

### Proposed solution

Add the ability to choose the preview/embed style -- either just the current line as blocks currently work or the entire "subtree" as headers currently work. 

This could potentially be accomplished by adding a single character to specify "full tree". It could be a double `!!`, for example: `!![[filename#^block_id]]`. 

It would be doubly neat if syntax maintains uniform usage with the behavior of heading links. (So, perhaps reversing the syntax above so the double `!!` does the single-block embed and single `!` does the entire subtree embed as headers do.)

So, in the end, usable syntax might be:

- Entire subtree: `![[filename#^block_subtree]]`
- Block-only Link: `!![[filename#^block_txt_only]]`.

**Comment by SeriousBug** [comment]
This feature has been completed. Please see [Block References](https://wiki.dendron.so/notes/f1af56bb-db27-47ae-8406-61a98de6c78c.html#block-anchor) in the wiki.

If you have any requests for features our current implementation doesn't cover, please create a [new feature request](https://github.com/dendronhq/dendron/issues/new/choose).
